### ISSUE TITLE
Jittery movement - Medium Priority

### ISSUE THREAD

**Issue by krain0** [UNLV-CS472-672/2024-F-GROUP2-ScaryGame-1#11]
## Issue Title
Jittery player movement

## Description
Sometimes when the player is walking, there is jittery movement.

### Steps to Reproduce

1. Walk anywhere on the map 
2. The camera view will be shaking

This happens somewhat unpredictably, see video below for example.
 
### Expected Behavior
The camera view should be smooth because the ground doesn't have any texture

### Actual Behavior
There is unpredictable shaking

## Environment
- **Unity Version:** 6000.0.14f1
- **Platform:**  Windows
- **Device Specs:** 16G Ram. Integrated Graphics card

## Screenshots
https://github.com/user-attachments/assets/d3d89aa7-6ade-40de-a7e3-152ca607e314

## Additional Context
This likely caused by using a character controller and rigidbody together https://docs.unity3d.com/6000.0/Documentation/Manual/class-CharacterController.html. Deleting the rigidbody resolves the issue for the most part, but jumping becomes slightly unnatural.

**Comment by computer-kyle** [comment]
This issue is still present as I had to re-add the Player RigidBody to resolve a merge conflict because the addition of a pause menu utilizes functions of the RigidBody. For my next PR, I will add a movement lock boolean to the PlayerMovement class which is modified by Brandon's title pause menu script, rather than RigidBody.
